source-file ~/.config/tmux/vague.conf
set -g status-position top

# Set Alt+a as prefix
set-option -g prefix M-a
unbind C-b
bind M-a send-prefix

bind-key -n M-t new-window
bind-key -n M-q kill-window
bind-key -n M-n next-window
bind-key -n M-p previous-window

bind-key -n M-s split-window -h
bind-key -n M-v split-window -v
bind-key -n M-x kill-pane
bind-key -n M-Left  select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up    select-pane -U
bind-key -n M-Down  select-pane -D
bind-key -n C-S-Left  resize-pane -L 5
bind-key -n C-S-Right resize-pane -R 5
bind-key -n C-S-Up    resize-pane -U 5
bind-key -n C-S-Down  resize-pane -D 5

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
set -g history-limit 100000
set-option -sa terminal-overrides ",xterm*:Tc"
#set -g default-terminal "xterm-256color" 
